services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: skindex
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - skindex
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d skindex"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/skindex
      DATABASE_USER: admin
      DATABASE_PASSWORD: secret
      ENV: local
      JWT_SECRET: some_unique_secret
      JWT_ISSUER: http://localhost:8080
      JWT_AUDIENCE: http://localhost:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - skindex
volumes:
  postgres_data:
networks:
  skindex:
    driver: bridge