version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/skindex?user=admin&password=secret
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=secret
      - ENV=local
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "sleep 10 && java -jar /app/backend.jar"]
    networks:
      - skindex

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=skindex
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST_AUTH_METHOD=md5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d skindex"]
      interval: 2s
      timeout: 5s
      retries: 15
    networks:
      - skindex

volumes:
  postgres_data:

networks:
  skindex:
    driver: bridge
